### ISSUE TITLE
Auswahl der Zwischen Ergebnisse als neuen Input

### ISSUE THREAD

**Issue by KWS89** [sydroconsult/QTalsim#10]
Momentan scheint es so, als ob man das Tool schrittweise durchlaufen lassen muss. Zwischen Ergebnisse können nicht ausgefählt werden um bei einem Arbeitsschritt wieder neu einzusteigen. Siehe Abbildung:
![Picture1](https://github.com/sydroconsult/QTalsim/assets/167743164/5e48b237-3580-4732-84c9-dad5a7ea293c)

**Comment by lorenz3tla** [comment]
The issue was addressed with the implementation in commit [0c1db65](https://github.com/sydroconsult/QTalsim/commit/0c1db656942c222c284638fca59ce348dfa2f8b6)
