### ISSUE TITLE
Function of button "Delete Overlapping Part of Selected Features" is unclear

### ISSUE THREAD

**Issue by jamaa** [sydroconsult/QTalsim#13]
When editing the land use layer in HRU calculation, it is not clear what the button "Delete Overlapping Part of Selected Features" does. It is not documented. What is the difference to using the button "Delete overlapping features"? In which layer does it check for selected features?

**Comment by lorenz3tla** [comment]
This button deletes the overlapping part of the selected feature in the table (https://sydroconsult.github.io/QTalsim/hrus_step_by_step.html#select-edit-soil-layer - Optional Soil Editing Steps).  This button only works if the user checked for overlapping features before that (button "Check for Overlapping Features"). Perhaps, it would be more intuitive if the 'Delete Overlapping Features' button was rephrased to 'Delete All Overlapping Features' and relocated, maybe below the table.
![DeleteOverlappingFeatures](https://github.com/sydroconsult/QTalsim/assets/90828435/3fa4b328-37c6-4506-98b9-35acf5c45011)

**Comment by jamaa** [comment]
Thanks, I guess I didn't read the docs closely enough
>Perhaps, it would be more intuitive if the 'Delete Overlapping Features' button was rephrased to 'Delete All Overlapping Features' and relocated, maybe below the table.

I agree with the rephrasing, but imo it can stay where it is
