### ISSUE TITLE
Display log messages panel automatically?

### ISSUE THREAD

**Issue by jamaa** [sydroconsult/QTalsim#16]
Most users don't know or notice that QTalsim writes log messages. Is it possible to automatically display the log message panel whenever QTalsim is started?

**Comment by lorenz3tla** [comment]
I could not find a solution for automatically displaying the panel yet. But for the start I could add a prompt that pops up when opening QTalsim, explaining the user how to open the panel?

**Comment by jamaa** [comment]
Hmm I think a prompt would be too intrusive. Maybe instead add a note about it to the docs?

**Comment by lorenz3tla** [comment]
Added a note in docs: https://sydroconsult.github.io/QTalsim/install_plugin.html
