### ISSUE TITLE
Add export to ASCII

### ISSUE THREAD

**Issue by jamaa** [sydroconsult/QTalsim#2]
The final step for being able to use the plugin output in Talsim is to export the tables as ASCII files with a particular format. I think this could be an optional button that can be used at the end of the workflow. Pressing this button should ask the user for the local directory to export to and for the filename to use. The plugin should then export the following files:
* `<filename>.LNZ`: https://www.talsim.de/docs/index.php?title=LNZ-Datei
* `<filename>.BOD`: https://www.talsim.de/docs/index.php?title=BOD-Datei
* `<filename>.BOA`: https://www.talsim.de/docs/index.php?title=BOA-Datei
* `<filename>.EFL`: https://www.talsim.de/docs/index.php?title=EFL-Datei

When exporting these files, it is important that the formatting is exactly as shown in the above links. Most parameter values have an exact space denoted by `<--->` in the header within which the value is allowed. Rounding floats to a certain length may be required. Also, the files must be encoded in iso-8859-1.

**Comment by nabdelwahab** [comment]
Sounds good!

**Comment by jamaa** [comment]
This was implemented in v1.1.0. If there is more to do, we can open new issues.
