### ISSUE TITLE
SVG symbols of SystemElement layer not working

### ISSUE THREAD

**Issue by jamaa** [sydroconsult/QTalsim#5]
in v1.2.0, the symbols of the SystemElement layer are not displayed properly.

Looks like the path to the SVG is wrong, contains the wrong username (see screenshot)

![grafik](https://github.com/sydroconsult/QTalsim/assets/90166/531a53fd-bb37-485d-928a-d5ded0f56262)

**Comment by lorenz3tla** [comment]
Fixed with v1.3.0.
