### ISSUE TITLE
Error when trying to view updated/new features

### ISSUE THREAD

**Issue by jamaa** [sydroconsult/QTalsim#6]
Affects v1.2.0

Clicking the button "Optional: view updated/new features in layer" causes the following error:

>2024-03-25T12:43:03     CRITICAL    'SQLConnectDialog' object has no attribute 'updatedElementsLayer'

**Comment by lorenz3tla** [comment]
Removed option to view updated/new features with v1.3.0, as it is not necessary anymore.
