### ISSUE TITLE
Allow different projections/coordinate systems for input layers

### ISSUE THREAD

**Issue by jamaa** [sydroconsult/QTalsim#8]
In v1.2.0, the input layer for updating sub-basins is assumed to be in WGS84. It would be nice if an arbitrary coordinate system is acceptable and conversion is done automatically. Alternatively (or if not easily possible) the plugin should emit a warning if the coordinate system is not as expected.

**Comment by lorenz3tla** [comment]
Implemented with v1.3.0.
